//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testeDrLavaTudoWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.OS = new HashSet<OS>();
        }
    
        public int IDCLIENTE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATANASC { get; set; }
        public string NOME { get; set; }
        public Nullable<long> TELCEL { get; set; }
        public Nullable<long> TELRES { get; set; }
        public Nullable<int> NUMEROIMOVEL { get; set; }
        public Nullable<long> CEP { get; set; }
    
        public virtual ENDERECO ENDERECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OS> OS { get; set; }
    }
}
