//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testeDrLavaTudoWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSITENS
    {
        public int IDOSIT { get; set; }
        public Nullable<int> IDOS { get; set; }
        public Nullable<int> IDSERVICO { get; set; }
        public Nullable<long> CEP { get; set; }
        public Nullable<System.DateTime> DATACONTRATACAO { get; set; }
        public Nullable<System.DateTime> DATAEXECUCAO { get; set; }
        public Nullable<int> NUMEROIMOVEL { get; set; }
    
        public virtual ENDERECO ENDERECO { get; set; }
        public virtual OS OS { get; set; }
        public virtual SERVICO SERVICO { get; set; }
    }
}
